FROM python:3.13-slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get -y update
RUN apt-get -y install git

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

EXPOSE 8001

# RUN useradd appuser && chown -R appuser /app
# USER appuser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]